src/register/register/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # register_foodのURLを追加
    path("register_food/", include("register_food.urls")),
]

src/register/register_food/urls.py
from django.urls import path

from .views import *

app_name = "register_food"
urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    # 新規登録
    path('entryform/', ProductCreateView.as_view(), name='entryform'),
    # 削除
    path('delete/', ProductDeleteView.as_view(), name='delete'),
    # 削除確認
    # path('delete_confirmation/', DeleteConfirmationView.as_view(), name='delete_confirmation'),
    # 更新
    path('update/', ProductUpdateView.as_view(), name='update'),
    # 更新処理実行確認
    path('update_confirmation/', ProductUpdateExcuteView.as_view(), name='update_confirmation'),
]

src/register/register_food/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=20)
    price = models.IntegerField()
    place = models.CharField(max_length=20)
    payment_date = models.DateTimeField()
    meal_format = models.PositiveIntegerField() # 0または正の整数
    category = models.CharField(max_length=20)
    degree_regret = models.IntegerField()

    def __str__(self):
        return self.product_name

src/register/register_food/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["title"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control", "placeholder": "卵を買う"}),
        }

src/register/register_food/views.py
from django.shortcuts import render, redirect, reverse,get_object_or_404 # 追加
from django.http import HttpResponseBadRequest # 追加
# Create your views here.
from django.views.generic.list import ListView
from django.views.generic import View
from .models import Product
from django.core import serializers

class ProductListView(View):
    def get(self,request):
        
        # Productデータを全件取得する。
        # TemplatesではproductListでアクセス可能
        productModel = {'products':Product.objects.all()} 

        return render(request, "register_food/product_list.html", productModel)

#-----新規登録処理を追加(20230801) From-------#
class ProductCreateView(View):
    def get(self, request):
        return render(request, 'register_food/product_form.html', {})
       
    def post(self, request):
        product_name = request.POST.get('product_name')
        price = request.POST.get('price')
        place = request.POST.get('place')
        payment_date = request.POST.get('payment_date')
        meal_format = request.POST.get('meal_format')
        category = request.POST.get('category')
        degree_regret = request.POST.get('degree_regret')

		# 変数のバリデーション
        if product_name and price and place and payment_date and meal_format and category and degree_regret:

			# データベースへの保存項目
            product = Product(
                product_name=product_name, 
                price=price, 
                place=place, 
                payment_date=payment_date,
                meal_format=meal_format,
                category=category,
                degree_regret=degree_regret,
                )

			# データベースへの保存
            product.save()

			# 登録後トップページに遷移
            return redirect('/register_food/')
        else:
			# バリデーションエラーの場合、バッドリクエストを表示する。
            return HttpResponseBadRequest("All fields are required")

#-----新規登録処理を追加(20230801) To -------#

#-----削除処理を追加(20230805) From -------#
# class ProductDeleteView(View):
#     def post(self, request):
#         selected_product_ids = request.POST.getlist('selected_products')
#         # __in演算子で指定されたリスト内の値に一致するものを取得する。
#         selected_products = Product.objects.filter(id__in=selected_product_ids)
#         if request.POST.get('confirm_delete'):
#             # 商品一覧画面で削除ボタン押下時に、セッションデータを設定する。
#             request.session['selected_products'] = selected_product_ids
#             return redirect(reverse('register_food:delete_confirmation'))

#         return render(request, 'register_food/product_delete.html', {'selected_products': selected_products})

# # 削除確認クラス
# # 削除確認画面から対象データを削除する。
# class DeleteConfirmationView(View):
#     def get(self, request):
#         # 選択された商品データ(プロダクトID)のセッション取得処理
#         selected_product_ids = request.session.get('selected_products')
#         selected_products = Product.objects.filter(id__in=selected_product_ids)
#         return render(request, 'register_food/product_delete.html', {'selected_products': selected_products})
    
#     def post(self, request):
#         # 選択された商品データ(プロダクトID)のセッション取得処理
#         selected_product_ids = request.session.get('selected_products')
#         selected_products = Product.objects.filter(id__in=selected_product_ids)

#         if request.POST.get('confirm_delete'):
#             # チェックされたデータの削除処理
#             selected_products.delete()
#             # セッションデータの削除
#             del request.session['selected_products']
#             # 商品一覧画面にリダイレクト
#             return redirect(reverse('register_food:product_list'))
#         return redirect(reverse('register_food:product_list'))
        
#-----削除処理を追加(20230805) To -------#


#-----削除と更新処理を追加(20230813) From -------#
class ProductUpdateView(View):
    # 更新処理の開始。確認画面を表示するためのビュー。
    # (POSTメソッドでデータが送信されたときの処理を記述)
    def post(self,request):
        #  チェックボックスで選択されたデータを取得
        selected_product_ids = request.POST.getlist('selected_products')
        # アクションタイプの取得
        action_type = request.POST.get('action_type')
        # チェックされたデータでフィルタリング
        selected_products = Product.objects.filter(id__in=selected_product_ids)
        
        if action_type == "update":
            # 商品一覧画面で更新ボタン押下時に、セッションデータを設定する。
            request.session['selected_products'] = selected_product_ids
            return redirect(reverse('register_food:update_confirmation'))

        return render(request, 'register_food/product_update.html', {'selected_products': selected_products})

class ProductUpdateExcuteView(View): 
    # 確認画面からデータを受け取り、商品情報を更新するためのビュー。
    def get(self, request):
        # 選択された商品データ(プロダクトID)のセッション取得処理
        selected_product_ids = request.session.get('selected_products')
        selected_products = Product.objects.filter(id__in=selected_product_ids)
        return render(request, 'register_food/product_update.html', {'selected_products': selected_products})
    
    def post(self, request):
        # 選択された商品データ(プロダクトID)のセッション取得処理
        selected_product_ids = request.session.get('selected_products')
        selected_products = Product.objects.filter(id__in=selected_product_ids)

        if request.POST.get('confirm_update'):
            # フォームデータを受け取り、商品情報を更新
            for product in selected_products:
                product.product_name = request.POST.get('product_name')
                product.price = request.POST.get('price')
                product.place = request.POST.get('place')
                product.payment_date = request.POST.get('payment_date')
                print(product.meal_format)
                print(request.POST.get('meal_format'))
                product.meal_format = request.POST.get('meal_format')
                
                product.category = request.POST.get('category')
                product.degree_regret = request.POST.get('degree_regret')
                # 他のフィールドも同様に更新
                product.save()
            # セッションデータの削除
            del request.session['selected_products']
            # 商品一覧画面にリダイレクト
            return redirect(reverse('register_food:product_list'))
        return redirect(reverse('register_food:product_list'))

class ProductDeleteView(View):
    def post(self,request):
        # チェックボックスで選択されたデータを取得
        selected_product_ids = request.POST.getlist('selected_products')
        # アクションタイプの取得
        action_type = request.POST.get('action_type')
        # selected_product_ids = request.POST.get('selected_products')

        # 削除処理の場合
        if action_type == "delete":
            # チェックされたデータでフィルタリング
            selected_products = Product.objects.filter(id__in=selected_product_ids)
            # 削除処理実行
            selected_products.delete()
            # 商品一覧画面にリダイレクト
            return redirect(reverse('register_food:product_list'))
        return redirect(reverse('register_food:product_list'))



#-----削除と更新処理を追加(20230813) To -------#

src/register/register_food/templates/register_food/product_delete.html
<h1>削除</h1>

<form method="post">
    {% csrf_token %}

    <p>
        以下の商品を削除してもよろしいですか？
    </p>
    <table border="1"> 
        <tr>
            <th>商品名</th>
            <th>購入場所</th>
            <th>購入日</th>
        </tr>
        {%for product in selected_products%}
        <tr>
            <td>{{product.product_name}}</td>
            <td>{{product.place}}</td>
            <td>{{product.payment_date}}</td>
        </tr>
        {% endfor %}
    </table>
    

    <a href="{% url 'register_food:product_list' %}">戻る</a>
    <input type="submit" name="confirm_delete" value="削除">
</form>

src/register/register_food/templates/register_food/product_form.html
<!-- product_form.html -->
<h1>新規登録</h1>

<form method="post">
{% csrf_token %}

<!-- 商品名 -->
<label for="product_name">商品名:</label>
<input type="text" name="product_name" id="product_name" value="{{ product.product_name }}" required>
<br>
<!-- 価格 -->
<label for="price">価格:</label>
<input type="number" name="price" id="price" min="0" value="{{ product.price }}" required>
<br>
<!-- 場所 -->
<label for="place">場所:</label>
<input type="text" name="place" id="place" value="{{ product.place }}" required>
<br>
<!-- 日にち -->
<label for="payment_date">日にち:</label>
<input type="date" name="payment_date" id="payment_date" value="{{ product.payment_date }}" required>
<br>
<!-- 食事形式 -->
<label for="meal_format">食事形式:</label>
<select name="meal_format" required>
<option value="">選択してください</option>
<option value="1">内食</option>
<option value="0">外食</option>
</select>
<br>
<!-- カテゴリ -->
<label for="category">カテゴリ:</label>
<textarea name="category" id="category" required>{{ product.category }}</textarea>
<br>
<!-- 後悔度 -->
<label for="degree_regret">後悔度:</label>
<input type="number" name="degree_regret" id="degree_regret" step="10" min="0" value="{{ product.degree_regret }}" required>
<br>
<!-- 戻るボタン-->
<a href="{% url 'register_food:product_list'%}">戻る</a>
<!-- 登録ボタン -->
<button type="submit">登録</button>
</form>

src/register/register_food/templates/register_food/product_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'register/style.css' %}">
    <title>productList</title>
  </head>
  <form method="post" id="mainForm" action="">
    <!-- アクションタイプを保存するhiddenパラメータ -->
    <input type="hidden" id="actionType" name="action_type" value="">
    <!-- チェックボックスで選択された商品データを保存するパラメータ -->
    <!-- <input type="hidden" id="selectedProducts" name="selected_products" value=""> -->
  {% csrf_token%}
  <body>
    <h1>商品一覧</h1>
    <!-- 表の枠線を設定する -->
    <table border="1"> 
        <tr>
            <th><input type="checkbox" name="headCheck" id="headCheck" onClick="checkAll()" /></th>
            <th>商品名</th>
            <th>価格</th>
            <th>購入場所</th>
            <th>購入日</th>
            <th>食事形式</th>
            <th>カテゴリ</th>
            <th>後悔度</th>
        </tr>
        {%for product in products%}
        <tr>
            <td><input type="checkbox" id="datachk" name="selected_products" value="{{ product.id }}" /></td>
            <td>{{product.product_name}}</td>
            <td>{{product.price}}</td>
            <td>{{product.place}}</td>
            <td>{{product.payment_date}}</td>
            <td>
              <!-- 食事形式が１の場合 -->
              {% if product.meal_format == 1%}
                内食
              {% else %}
              <!-- 食事形式が１以外の場合 -->
                外食
              {% endif %}
            </td>
            <td>{{product.category}}</td>
            <td>{{product.degree_regret}}</td>
            
        </tr>
        {% endfor %}
    </table>
    <div>
      <!-- 登録ボタン -->
      <a href="{% url 'register_food:entryform' %}" class="btn">新規登録</a>
      <!-- 更新ボタン -->            
      <button type="button" id="updateButton" data-update-url="{% url 'register_food:update' %}">更新</button>
      <!-- 削除ボタン -->            
      <button type="button" id="deleteButton" data-delete-url="{% url 'register_food:delete' %}">削除</button>
    </div>



    <!-- ここにJavaScriptを読み込むコード -->
    <script src="{% static 'register/register.js' %}"></script>
  </body>
</form>
</html>

src/register/register_food/templates/register_food/product_update.html
<h1>更新</h1>

<form method="post" action="{% url 'register_food:update_confirmation' %}">
    {% csrf_token %}

    <p>
        更新対象の項目を編集して、実行ボタンを押下してください
    </p>
    <!-- 商品名 -->

    {%for product in selected_products%}
    <label for="product_name">商品名:</label>
    <input type="text" name="product_name" id="product_name" value="{{ product.product_name }}" required>
    <br>
    <!-- 価格 -->
    <label for="price">価格:</label>
    <input type="number" name="price" id="price" min="0" value="{{ product.price }}" required>
    <br>
    <!-- 場所 -->
    <label for="place">場所:</label>
    <input type="text" name="place" id="place" value="{{ product.place }}" required>
    <br>
    <!-- 日にち -->
    <label for="payment_date">日にち:</label>
    <input type="date" name="payment_date" id="payment_date" value="{{ product.payment_date }}" required>
    <br>
    <!-- 食事形式 -->
    <label for="meal_format">食事形式:</label>
    <select name="meal_format" required>
    <option value="">選択してください</option>
    <option value="1">内食</option>
    <option value="0">外食</option>
    </select>
    <br>
    <!-- カテゴリ -->
    <label for="category">カテゴリ:</label>
    <textarea name="category" id="category" required>{{ product.category }}</textarea>
    <br>
    <!-- 後悔度 -->
    <label for="degree_regret">後悔度:</label>
    <input type="number" name="degree_regret" id="degree_regret" step="10" min="0" value="{{ product.degree_regret }}" required>
    
    {% endfor %}
    

    <div>
    <a href="{% url 'register_food:product_list' %}">戻る</a>
    <input type="submit" name="confirm_update" value="実行">
    </div>
</form>